name: template
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      postgres_timescaledb:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ../log:/log
